# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Pa55w0rd2020"
      ACCEPT_EULA: "Y"
  redis:
    image: redis
    ports: 
      - 6379:6379  
  api:
    image: api:v1.0.0
    container_name: api
    working_dir: /app
    volumes:
      - ./:/app
    command: "dotnet run"
    ports:
      - 5000:5000
    depends_on:
      - sql-server-db
    environment:
      ServerName : "sql-server-db"
      Database : "altamiraDb"
      UserName : "SA"
      Password : "Pa55w0rd2020"
      RedisConnectionString : "localhost:6379"
